"use client";

import { useQuery } from "@tanstack/react-query";
import { api } from "@/lib/api";
import { Suspense } from "react";
import { 
  Table, 
  TableBody, 
  TableCell, 
  TableHead, 
  TableHeader, 
  TableRow 
} from "@/components/ui/table";
import { 
  Search, 
  Filter, 
  Download, 
  CheckCircle2, 
  Clock, 
  AlertCircle, 
  FileText,
  ChevronRight,
  MoreHorizontal,
  ExternalLink,
  Trash2,
  TrendingUp,
  Plus
} from "lucide-react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { 
  DropdownMenu, 
  DropdownMenuContent, 
  DropdownMenuItem, 
  DropdownMenuLabel, 
  DropdownMenuSeparator, 
  DropdownMenuTrigger 
} from "@/components/ui/dropdown-menu";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { useSearchParams, useRouter, usePathname } from "next/navigation";
import { useState, useMemo, useEffect } from "react";
import { format } from "date-fns";
import { useClientContext } from "@/components/providers/client-provider";

function AllInvoicesPageContent() {
  const { activeClient } = useClientContext();
  const searchParams = useSearchParams();
  const router = useRouter();
  const pathname = usePathname();

  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState(() => {
    const status = searchParams.get("status");
    return status ? status.toUpperCase() : "ALL";
  });

  const { data: initialInvoices, isLoading } = useQuery({
    queryKey: ["invoices"],
    queryFn: api.invoices.list,
  });

  const [invoices, setInvoices] = useState<any[]>([]);

  useEffect(() => {
    if (initialInvoices) {
      setInvoices(initialInvoices);
    }
  }, [initialInvoices]);

  const handleUpdateStatus = (invoiceId: string, newStatus: string) => {
    setInvoices(prev => prev.map(inv => 
      inv.id === invoiceId ? { ...inv, status: newStatus } : inv
    ));
  };

  // Reactive sync with URL
  useEffect(() => {
    const status = searchParams.get("status");
    const normalizedStatus = status ? status.toUpperCase() : "ALL";
    if (normalizedStatus !== statusFilter) {
      setStatusFilter(normalizedStatus);
    }
  }, [searchParams, statusFilter]);

  const handleStatusChange = (value: string) => {
    const params = new URLSearchParams(searchParams.toString());
    if (value === "ALL") {
      params.delete("status");
    } else {
      params.set("status", value.toLowerCase());
    }
    router.replace(`${pathname}?${params.toString()}`, { scroll: false });
  };

  const filteredInvoices = useMemo(() => {
    if (!invoices) return [];
    return invoices.filter(inv => {
      const matchesClient = !activeClient || inv.client_id === activeClient.id;
      const matchesSearch = inv.billing_month.toLowerCase().includes(search.toLowerCase()) ||
                            inv.id.toLowerCase().includes(search.toLowerCase());
      const matchesStatus = statusFilter === "ALL" || inv.status === statusFilter;
      return matchesClient && matchesSearch && matchesStatus;
    });
  }, [invoices, search, statusFilter, activeClient]);

  const getStatusConfig = (status: string) => {
    switch (status) {
      case "PAID":
        return { color: "bg-emerald-500/10 text-emerald-500 border-emerald-500/20", icon: CheckCircle2 };
      case "OVERDUE":
        return { color: "bg-destructive/10 text-destructive border-destructive/20", icon: AlertCircle };
      case "SENT":
        return { color: "bg-blue-500/10 text-blue-500 border-blue-500/20", icon: FileText };
      case "APPROVED":
        return { color: "bg-indigo-500/10 text-indigo-500 border-indigo-500/20", icon: CheckCircle2 };
      case "DRAFT":
        return { color: "bg-slate-500/10 text-slate-500 border-slate-500/20", icon: Clock };
      default:
        return { color: "bg-primary/10 text-primary border-primary/20", icon: FileText };
    }
  };

  if (isLoading) {
    return <InvoicesListSkeleton />;
  }

  return (
    <div className="space-y-8 pb-10">
      <div className="px-2">
        <h1 className="text-4xl font-black tracking-tight text-foreground mb-2">All Invoices</h1>
        <p className="text-muted-foreground text-sm font-medium">Browse and filter every invoice generated by the system.</p>
      </div>

      {/* Filter Bar */}
      <div className="flex flex-col md:flex-row gap-4 px-2">
        <div className="relative flex-1 group">
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 size-4 text-muted-foreground group-focus-within:text-primary transition-colors" />
          <Input 
            placeholder="Search by ID or billing month..." 
            className="h-12 pl-11 pr-4 bg-card border-border/50 rounded-xl focus-visible:ring-primary/20 transition-all shadow-sm"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
        <div className="flex gap-2 p-1 bg-muted/30 rounded-xl border border-border/50 overflow-x-auto no-scrollbar">
           {["ALL", "DRAFT", "APPROVED", "SENT", "PAID", "OVERDUE"].map((status) => (
              <button
                key={status}
                onClick={() => handleStatusChange(status)}
                className={`px-4 py-2 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all ${
                  statusFilter === status 
                    ? "bg-white text-primary shadow-sm ring-1 ring-border/50 dark:bg-primary dark:text-primary-foreground" 
                    : "text-muted-foreground hover:bg-white/50 dark:hover:bg-white/5"
                }`}
              >
                {status}
              </button>
           ))}
        </div>
      </div>

      {/* Invoices List */}
      <div className="grid gap-3 px-2">
        {filteredInvoices.map((inv) => {
          const status = getStatusConfig(inv.status);
          const StatusIcon = status.icon;

          return (
            <Card key={inv.id} className="group border-border/40 bg-card hover:shadow-xl hover:shadow-primary/5 hover:border-primary/20 transition-all duration-300 rounded-xl overflow-hidden">
               <CardContent className="p-0">
                  <div className="flex flex-col md:flex-row items-center p-6 gap-6">
                     <div className="size-14 rounded-xl bg-muted/30 flex items-center justify-center shrink-0 group-hover:bg-primary/10 transition-colors">
                        <FileText className="size-7 text-muted-foreground group-hover:text-primary transition-colors" />
                     </div>
                     
                     <div className="flex-1 min-w-0 text-center md:text-left">
                        <div className="flex flex-col md:flex-row md:items-center gap-2 mb-1">
                           <h3 className="font-black text-lg tracking-tight truncate">Invoice #{inv.id.slice(0, 8)}</h3>
                           <Badge variant="outline" className={`w-fit mx-auto md:mx-0 px-2.5 py-0.5 rounded-full text-[10px] font-black uppercase tracking-widest border transition-colors ${status.color}`}>
                              <StatusIcon className="size-3 mr-1.5" />
                              {inv.status}
                           </Badge>
                        </div>
                        <div className="flex flex-wrap justify-center md:justify-start gap-4">
                           <div className="flex items-center gap-1.5 text-[11px] font-bold text-muted-foreground">
                              <Clock className="size-3.5" />
                              {inv.billing_month}
                           </div>
                           <div className="flex items-center gap-1.5 text-[11px] font-bold text-muted-foreground">
                              <TrendingUp className="size-3.5" />
                              {inv.currency}
                           </div>
                        </div>
                     </div>

                     <div className="flex flex-col items-center md:items-end gap-1 px-8 border-x border-border/30">
                        <span className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60 leading-none">Total Amount</span>
                        <div className="text-2xl font-black tabular-nums tracking-tighter">
                           ${inv.total_amount.toLocaleString()}
                        </div>
                     </div>

                     <div className="flex items-center gap-2">
                        <Button variant="ghost" size="icon" className="size-11 rounded-xl hover:bg-primary/10 hover:text-primary transition-all">
                           <Download className="size-5" />
                        </Button>
                        <DropdownMenu>
                           <DropdownMenuTrigger asChild>
                              <Button variant="ghost" size="icon" className="size-11 rounded-xl transition-all">
                                 <MoreHorizontal className="size-5" />
                              </Button>
                           </DropdownMenuTrigger>
                           <DropdownMenuContent align="end" className="bg-popover/90 backdrop-blur-xl border-border rounded-xl">
                              <DropdownMenuLabel className="px-3 py-2 text-[10px] font-bold uppercase tracking-widest text-muted-foreground">Invoice Options</DropdownMenuLabel>
                              <DropdownMenuItem className="gap-2 cursor-pointer font-bold rounded-lg">
                                 <ExternalLink className="size-4" /> View Details
                              </DropdownMenuItem>
                              <DropdownMenuItem className="gap-2 cursor-pointer font-bold rounded-lg">
                                 <Plus className="size-4" /> Manage Items
                              </DropdownMenuItem>
                              <DropdownMenuSeparator />
                              <DropdownMenuLabel className="px-3 py-2 text-[10px] font-bold uppercase tracking-widest text-muted-foreground">Change Status</DropdownMenuLabel>
                              <DropdownMenuItem 
                                className="gap-2 cursor-pointer font-bold rounded-lg text-emerald-500 focus:bg-emerald-500/10"
                                onClick={() => handleUpdateStatus(inv.id, "PAID")}
                              >
                                 <CheckCircle2 className="size-4" /> Mark as Paid
                              </DropdownMenuItem>
                              <DropdownMenuItem 
                                className="gap-2 cursor-pointer font-bold rounded-lg text-blue-500 focus:bg-blue-500/10"
                                onClick={() => handleUpdateStatus(inv.id, "SENT")}
                              >
                                 <FileText className="size-4" /> Move to Sent
                              </DropdownMenuItem>
                              <DropdownMenuItem 
                                className="gap-2 cursor-pointer font-bold rounded-lg text-indigo-500 focus:bg-indigo-500/10"
                                onClick={() => handleUpdateStatus(inv.id, "APPROVED")}
                              >
                                 <CheckCircle2 className="size-4" /> Approve
                              </DropdownMenuItem>
                              <DropdownMenuItem 
                                className="gap-2 cursor-pointer font-bold rounded-lg text-rose-500 focus:bg-rose-500/10"
                                onClick={() => handleUpdateStatus(inv.id, "OVERDUE")}
                              >
                                 <AlertCircle className="size-4" /> Mark Overdue
                              </DropdownMenuItem>
                              <DropdownMenuSeparator />
                              <DropdownMenuItem className="gap-2 cursor-pointer font-bold text-destructive focus:bg-destructive/10 rounded-lg">
                                 <Trash2 className="size-4" /> Void Invoice
                              </DropdownMenuItem>
                           </DropdownMenuContent>
                        </DropdownMenu>
                     </div>
                  </div>
               </CardContent>
            </Card>
          );
        })}

        {filteredInvoices.length === 0 && (
          <div className="py-20 flex flex-col items-center justify-center bg-card border border-dashed border-border rounded-xl">
            <div className="size-16 rounded-full bg-muted/30 flex items-center justify-center mb-4">
              <Search className="size-8 text-muted-foreground/40" />
            </div>
            <h3 className="text-xl font-black tracking-tight text-foreground">No invoices found</h3>
            <p className="text-muted-foreground text-sm font-medium">Try adjusting your filters or search terms.</p>
          </div>
        )}
      </div>
    </div>
  );
}


function InvoicesListSkeleton() {
  return (
    <div className="space-y-8 pb-10">
      <div className="px-2">
        <Skeleton className="h-10 w-48 rounded-xl mb-2" />
        <Skeleton className="h-4 w-96 rounded-xl" />
      </div>

      <div className="flex flex-col md:flex-row gap-4 px-2">
        <Skeleton className="h-12 w-full rounded-xl" />
        <Skeleton className="h-12 w-full max-w-md rounded-xl" />
      </div>

      <div className="space-y-4 px-2">
        {[...Array(5)].map((_, i) => (
          <Skeleton key={i} className="h-20 w-full rounded-xl" />
        ))}
      </div>
    </div>
  );
}

export default function AllInvoicesPage() {
  return (
    <Suspense fallback={<InvoicesListSkeleton />}>
      <AllInvoicesPageContent />
    </Suspense>
  );
}
